### ISSUE TITLE
authors_georef() 'expected 'a real' got <html>'

### ISSUE THREAD

**Issue by aurielfournier** [embruna/refnet#45]
```r
WOS18_georef <- authors_georef(data=WOS18_refine)
[1] "Trying data science toolkit first..."
Error in scan("http://www.datasciencetoolkit.org", nlines = 1) : 
  scan() expected 'a real', got '<html>'
```

**Comment by aurielfournier** [comment]
```r
  check.open <- NA
  print("Trying data science toolkit first...")
  check.open <- tryCatch(scan("http://www.datasciencetoolkit.org", nlines = 1), warning = function(w) {
    w
  })
```

This is where the issue is coming from `scan()` throws the error.

I'm not familiar with `scan()`, @birderboone is it possible we need to import a different scan function? The one we are using is from base R.

**Comment by birderboone** [comment]
So the answer to this is that scan is related to readLines, its like a base level read.table function. You can, or sort of, use it to read website html as well. I simply needed a quick ping to make sure I got a response. This was supposed to get quick scan of the html and make sure something was returned. However, it works weird. It will return an error sometimes when the website is down, and other times it will return the html OF THE 404...not found webpage. So it never really worked as intended. 

The function instead does an actual system ping, which seems to work, and hopefully is OS robust.

**Comment by birderboone** [comment]
Windows is actually a bit erratic with system commands now a days, and you cant always send it system commands like you used to. I dont completely understand why, it doesnt properly capture or open a shell when called. Where as linux does this perfectly. So i open this works on Mac, because im assuming windows is the hard one to please in this scenario. But its something to remember.
